export interface MenuItem {
  name: string
  price: number
  description: string
  isVeg: boolean
  isBestseller?: boolean
}

export interface Restaurant {
  id: string
  name: string
  city: string
  cuisineType: string
  rating: number
  deliveryTime: string
  priceRange: string
  image: string
  isPromoted?: boolean
  discount?: string
  menuItems: MenuItem[]
}

export const cities = ["All Cities", "Mumbai", "Delhi", "Bangalore", "Chennai", "Kolkata", "Hyderabad"]

export const cuisineFilters = [
  "All",
  "North Indian",
  "South Indian",
  "Chinese",
  "Italian",
  "Continental",
  "Fast Food",
  "Desserts",
  "Biryani",
]

export const restaurants: Restaurant[] = [
  // Mumbai Restaurants
  {
    id: "1",
    name: "Taj Mahal Palace Kitchen",
    city: "Mumbai",
    cuisineType: "North Indian",
    rating: 4.8,
    deliveryTime: "25-30 min",
    priceRange: "₹₹₹",
    image: "/luxury-indian-restaurant-interior-with-warm-lighti.jpg",
    isPromoted: true,
    discount: "20% OFF up to ₹100",
    menuItems: [
      {
        name: "Butter Chicken",
        price: 420,
        description: "Creamy tomato-based chicken curry",
        isVeg: false,
        isBestseller: true,
      },
      {
        name: "Dal Makhani",
        price: 280,
        description: "Slow-cooked black lentils in cream",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Garlic Naan", price: 60, description: "Soft bread with garlic butter", isVeg: true },
      { name: "Paneer Tikka", price: 320, description: "Grilled cottage cheese with spices", isVeg: true },
    ],
  },
  {
    id: "2",
    name: "Bamboo Garden",
    city: "Mumbai",
    cuisineType: "Chinese",
    rating: 4.5,
    deliveryTime: "30-35 min",
    priceRange: "₹₹",
    image: "/modern-chinese-restaurant-with-bamboo-decor.jpg",
    discount: "15% OFF on first order",
    menuItems: [
      {
        name: "Kung Pao Chicken",
        price: 350,
        description: "Spicy diced chicken with peanuts",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Veg Manchurian", price: 220, description: "Crispy vegetable balls in tangy sauce", isVeg: true },
      { name: "Hakka Noodles", price: 180, description: "Stir-fried noodles with vegetables", isVeg: true },
      { name: "Dim Sum Platter", price: 280, description: "Assorted steamed dumplings", isVeg: false },
    ],
  },
  {
    id: "3",
    name: "Pizza Paradise",
    city: "Mumbai",
    cuisineType: "Italian",
    rating: 4.3,
    deliveryTime: "35-40 min",
    priceRange: "₹₹",
    image: "/cozy-italian-pizzeria-with-wood-fired-oven.jpg",
    menuItems: [
      {
        name: "Margherita Pizza",
        price: 299,
        description: "Classic tomato, mozzarella, basil",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Pepperoni Feast", price: 449, description: "Loaded with premium pepperoni", isVeg: false },
      { name: "Pasta Alfredo", price: 320, description: "Creamy white sauce pasta", isVeg: true },
      { name: "Garlic Bread", price: 149, description: "Crispy bread with garlic butter", isVeg: true },
    ],
  },
  {
    id: "4",
    name: "South Spice",
    city: "Mumbai",
    cuisineType: "South Indian",
    rating: 4.6,
    deliveryTime: "20-25 min",
    priceRange: "₹",
    image: "/traditional-south-indian-restaurant-with-banana-le.jpg",
    isPromoted: true,
    menuItems: [
      {
        name: "Masala Dosa",
        price: 120,
        description: "Crispy crepe with spiced potato",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Idli Sambar", price: 80, description: "Steamed rice cakes with lentil soup", isVeg: true },
      { name: "Medu Vada", price: 70, description: "Crispy lentil doughnuts", isVeg: true },
      { name: "Filter Coffee", price: 50, description: "Authentic South Indian coffee", isVeg: true },
    ],
  },
  {
    id: "5",
    name: "Burger Barn",
    city: "Mumbai",
    cuisineType: "Fast Food",
    rating: 4.2,
    deliveryTime: "15-20 min",
    priceRange: "₹",
    image: "/american-style-burger-restaurant-with-neon-lights.jpg",
    discount: "Buy 1 Get 1 Free",
    menuItems: [
      {
        name: "Classic Cheeseburger",
        price: 199,
        description: "Beef patty with melted cheese",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Veggie Delight", price: 149, description: "Grilled veggie patty burger", isVeg: true },
      { name: "Crispy Fries", price: 99, description: "Golden crispy potato fries", isVeg: true },
      { name: "Chocolate Shake", price: 129, description: "Thick chocolate milkshake", isVeg: true },
    ],
  },
  {
    id: "6",
    name: "Royal Biryani House",
    city: "Mumbai",
    cuisineType: "Biryani",
    rating: 4.7,
    deliveryTime: "40-45 min",
    priceRange: "₹₹",
    image: "/aromatic-biryani-restaurant-with-traditional-decor.jpg",
    isPromoted: true,
    discount: "₹50 OFF on orders above ₹500",
    menuItems: [
      {
        name: "Hyderabadi Chicken Biryani",
        price: 320,
        description: "Fragrant basmati rice with tender chicken",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Veg Dum Biryani", price: 250, description: "Aromatic vegetable biryani", isVeg: true },
      { name: "Mutton Biryani", price: 420, description: "Rich and flavorful goat meat biryani", isVeg: false },
      { name: "Raita", price: 60, description: "Cool yogurt with cucumber", isVeg: true },
    ],
  },
  {
    id: "7",
    name: "Sweet Dreams",
    city: "Mumbai",
    cuisineType: "Desserts",
    rating: 4.4,
    deliveryTime: "25-30 min",
    priceRange: "₹₹",
    image: "/images/ads/dessert-cafe-ad.png",
    menuItems: [
      {
        name: "Belgian Chocolate Cake",
        price: 180,
        description: "Rich dark chocolate layered cake",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Gulab Jamun", price: 120, description: "Soft milk dumplings in sugar syrup", isVeg: true },
      { name: "Cheesecake", price: 220, description: "New York style creamy cheesecake", isVeg: true },
      { name: "Ice Cream Sundae", price: 160, description: "Mixed ice cream with toppings", isVeg: true },
    ],
  },
  {
    id: "8",
    name: "Continental Corner",
    city: "Mumbai",
    cuisineType: "Continental",
    rating: 4.5,
    deliveryTime: "35-40 min",
    priceRange: "₹₹₹",
    image: "/upscale-continental-restaurant-with-elegant-platin.jpg",
    menuItems: [
      {
        name: "Grilled Salmon",
        price: 650,
        description: "Pan-seared salmon with lemon butter",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Mushroom Risotto", price: 380, description: "Creamy Italian rice with mushrooms", isVeg: true },
      { name: "Caesar Salad", price: 280, description: "Romaine lettuce with Caesar dressing", isVeg: true },
      { name: "Chicken Steak", price: 450, description: "Grilled chicken breast with herbs", isVeg: false },
    ],
  },
  {
    id: "9",
    name: "Tandoor Tales",
    city: "Mumbai",
    cuisineType: "North Indian",
    rating: 4.4,
    deliveryTime: "30-35 min",
    priceRange: "₹₹",
    image: "/rustic-north-indian-tandoor-restaurant.jpg",
    menuItems: [
      {
        name: "Tandoori Chicken",
        price: 380,
        description: "Clay oven roasted spiced chicken",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Seekh Kebab", price: 320, description: "Minced meat skewers", isVeg: false },
      { name: "Paneer Butter Masala", price: 280, description: "Cottage cheese in rich tomato gravy", isVeg: true },
      { name: "Rumali Roti", price: 40, description: "Thin handkerchief bread", isVeg: true },
    ],
  },
  {
    id: "10",
    name: "Wok Express",
    city: "Mumbai",
    cuisineType: "Chinese",
    rating: 4.1,
    deliveryTime: "20-25 min",
    priceRange: "₹",
    image: "/fast-casual-chinese-wok-station.jpg",
    discount: "Flat 30% OFF",
    menuItems: [
      {
        name: "Schezwan Fried Rice",
        price: 180,
        description: "Spicy stir-fried rice",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Chilli Chicken", price: 250, description: "Crispy chicken in chilli sauce", isVeg: false },
      { name: "Spring Rolls", price: 150, description: "Crispy vegetable rolls", isVeg: true },
      { name: "Hot & Sour Soup", price: 120, description: "Tangy and spicy soup", isVeg: true },
    ],
  },
  // Delhi Restaurants
  {
    id: "11",
    name: "Old Delhi Delights",
    city: "Delhi",
    cuisineType: "North Indian",
    rating: 4.9,
    deliveryTime: "25-30 min",
    priceRange: "₹₹",
    image: "/historic-old-delhi-street-food-restaurant.jpg",
    isPromoted: true,
    discount: "25% OFF on weekends",
    menuItems: [
      {
        name: "Chole Bhature",
        price: 150,
        description: "Spicy chickpeas with fried bread",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Paranthe", price: 80, description: "Stuffed Indian flatbreads", isVeg: true },
      { name: "Lassi", price: 60, description: "Sweet yogurt drink", isVeg: true },
      { name: "Jalebi", price: 100, description: "Crispy sweet spirals", isVeg: true },
    ],
  },
  {
    id: "12",
    name: "Dragon House",
    city: "Delhi",
    cuisineType: "Chinese",
    rating: 4.4,
    deliveryTime: "30-35 min",
    priceRange: "₹₹",
    image: "/authentic-chinese-restaurant-with-red-lanterns.jpg",
    menuItems: [
      {
        name: "Sweet & Sour Pork",
        price: 380,
        description: "Crispy pork in tangy sauce",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Veg Spring Rolls", price: 180, description: "Crispy vegetable rolls", isVeg: true },
      { name: "Chow Mein", price: 220, description: "Stir-fried noodles", isVeg: true },
      { name: "Wonton Soup", price: 150, description: "Clear soup with dumplings", isVeg: false },
    ],
  },
  {
    id: "13",
    name: "La Piazza",
    city: "Delhi",
    cuisineType: "Italian",
    rating: 4.6,
    deliveryTime: "35-40 min",
    priceRange: "₹₹₹",
    image: "/elegant-italian-trattoria-with-terracotta.jpg",
    isPromoted: true,
    menuItems: [
      { name: "Quattro Formaggi", price: 520, description: "Four cheese pizza", isVeg: true, isBestseller: true },
      { name: "Lasagna", price: 450, description: "Layered pasta with meat sauce", isVeg: false },
      { name: "Tiramisu", price: 280, description: "Classic Italian dessert", isVeg: true },
      { name: "Bruschetta", price: 220, description: "Toasted bread with tomatoes", isVeg: true },
    ],
  },
  {
    id: "14",
    name: "Dakshin Flavors",
    city: "Delhi",
    cuisineType: "South Indian",
    rating: 4.3,
    deliveryTime: "25-30 min",
    priceRange: "₹",
    image: "/bright-south-indian-tiffin-center.jpg",
    menuItems: [
      { name: "Rava Dosa", price: 100, description: "Crispy semolina crepe", isVeg: true, isBestseller: true },
      { name: "Uttapam", price: 90, description: "Thick rice pancake with toppings", isVeg: true },
      { name: "Pongal", price: 80, description: "Rice and lentil porridge", isVeg: true },
      { name: "Rasam", price: 50, description: "Spicy tamarind soup", isVeg: true },
    ],
  },
  {
    id: "15",
    name: "Shake Shack Delhi",
    city: "Delhi",
    cuisineType: "Fast Food",
    rating: 4.5,
    deliveryTime: "20-25 min",
    priceRange: "₹₹",
    image: "/modern-burger-joint-with-industrial-design.jpg",
    discount: "Free drink with combo",
    menuItems: [
      { name: "Shack Burger", price: 350, description: "Signature beef burger", isVeg: false, isBestseller: true },
      { name: "Crinkle Fries", price: 150, description: "Crispy crinkle-cut fries", isVeg: true },
      { name: "Concrete", price: 200, description: "Frozen custard blend", isVeg: true },
      { name: "Hot Dog", price: 280, description: "Classic beef hot dog", isVeg: false },
    ],
  },
  {
    id: "16",
    name: "Biryani Blues",
    city: "Delhi",
    cuisineType: "Biryani",
    rating: 4.7,
    deliveryTime: "35-40 min",
    priceRange: "₹₹",
    image: "/traditional-biryani-handi-setup.jpg",
    isPromoted: true,
    menuItems: [
      {
        name: "Lucknowi Biryani",
        price: 340,
        description: "Light and fragrant awadhi style",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Egg Biryani", price: 220, description: "Biryani with boiled eggs", isVeg: false },
      { name: "Phirni", price: 80, description: "Creamy rice pudding", isVeg: true },
      { name: "Shami Kebab", price: 180, description: "Tender meat patties", isVeg: false },
    ],
  },
  {
    id: "17",
    name: "Dessert Studio",
    city: "Delhi",
    cuisineType: "Desserts",
    rating: 4.6,
    deliveryTime: "30-35 min",
    priceRange: "₹₹",
    image: "/chic-dessert-boutique-with-macarons.jpg",
    menuItems: [
      {
        name: "Red Velvet Cake",
        price: 200,
        description: "Cream cheese frosted cake",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Macarons Box", price: 350, description: "Assorted French macarons", isVeg: true },
      { name: "Brownie Sundae", price: 180, description: "Warm brownie with ice cream", isVeg: true },
      { name: "Churros", price: 150, description: "Cinnamon sugar coated", isVeg: true },
    ],
  },
  {
    id: "18",
    name: "The Global Kitchen",
    city: "Delhi",
    cuisineType: "Continental",
    rating: 4.4,
    deliveryTime: "40-45 min",
    priceRange: "₹₹₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Lamb Chops", price: 720, description: "Herb-crusted lamb rack", isVeg: false, isBestseller: true },
      { name: "Seafood Pasta", price: 480, description: "Mixed seafood in white wine", isVeg: false },
      { name: "Grilled Vegetables", price: 320, description: "Seasonal vegetables platter", isVeg: true },
      { name: "Crème Brûlée", price: 250, description: "Classic French dessert", isVeg: true },
    ],
  },
  {
    id: "19",
    name: "Punjabi Tadka",
    city: "Delhi",
    cuisineType: "North Indian",
    rating: 4.5,
    deliveryTime: "25-30 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    discount: "₹75 OFF on ₹400+",
    menuItems: [
      { name: "Sarson Ka Saag", price: 220, description: "Mustard greens curry", isVeg: true, isBestseller: true },
      { name: "Makki Ki Roti", price: 40, description: "Corn flour flatbread", isVeg: true },
      { name: "Amritsari Fish", price: 380, description: "Crispy fried fish", isVeg: false },
      { name: "Lassi", price: 80, description: "Thick sweet yogurt", isVeg: true },
    ],
  },
  {
    id: "20",
    name: "Noodle Bar",
    city: "Delhi",
    cuisineType: "Chinese",
    rating: 4.2,
    deliveryTime: "25-30 min",
    priceRange: "₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Dan Dan Noodles", price: 220, description: "Spicy Sichuan noodles", isVeg: false, isBestseller: true },
      { name: "Vegetable Ramen", price: 250, description: "Japanese style soup noodles", isVeg: true },
      { name: "Gyoza", price: 180, description: "Pan-fried dumplings", isVeg: false },
      { name: "Edamame", price: 120, description: "Salted soy beans", isVeg: true },
    ],
  },
  // Bangalore Restaurants
  {
    id: "21",
    name: "Garden City Grills",
    city: "Bangalore",
    cuisineType: "Continental",
    rating: 4.7,
    deliveryTime: "35-40 min",
    priceRange: "₹₹₹",
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    menuItems: [
      {
        name: "Ribeye Steak",
        price: 850,
        description: "Prime cut with peppercorn sauce",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Truffle Pasta", price: 520, description: "Fettuccine with truffle oil", isVeg: true },
      { name: "Greek Salad", price: 280, description: "Fresh Mediterranean salad", isVeg: true },
      { name: "Tiramisu", price: 300, description: "Authentic Italian dessert", isVeg: true },
    ],
  },
  {
    id: "22",
    name: "MTR Heritage",
    city: "Bangalore",
    cuisineType: "South Indian",
    rating: 4.9,
    deliveryTime: "20-25 min",
    priceRange: "₹",
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    discount: "Legendary since 1924",
    menuItems: [
      {
        name: "MTR Special Masala Dosa",
        price: 150,
        description: "Signature crispy dosa",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Bisi Bele Bath", price: 130, description: "Spicy rice with lentils", isVeg: true },
      { name: "Rava Idli", price: 100, description: "Semolina idli with ghee", isVeg: true },
      { name: "Badam Halwa", price: 120, description: "Almond dessert", isVeg: true },
    ],
  },
  {
    id: "23",
    name: "Spice Route",
    city: "Bangalore",
    cuisineType: "North Indian",
    rating: 4.4,
    deliveryTime: "30-35 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Rogan Josh", price: 420, description: "Kashmiri lamb curry", isVeg: false, isBestseller: true },
      { name: "Shahi Paneer", price: 300, description: "Royal paneer in cream", isVeg: true },
      { name: "Biryani", price: 350, description: "Fragrant rice with meat", isVeg: false },
      { name: "Naan Basket", price: 150, description: "Assorted breads", isVeg: true },
    ],
  },
  {
    id: "24",
    name: "Wok & Roll",
    city: "Bangalore",
    cuisineType: "Chinese",
    rating: 4.3,
    deliveryTime: "25-30 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    discount: "20% OFF after 9 PM",
    menuItems: [
      {
        name: "Crispy Honey Chicken",
        price: 340,
        description: "Sweet glazed chicken",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Thai Green Curry", price: 300, description: "Coconut based curry", isVeg: true },
      { name: "Pad Thai", price: 280, description: "Stir-fried Thai noodles", isVeg: true },
      { name: "Mango Sticky Rice", price: 180, description: "Thai dessert", isVeg: true },
    ],
  },
  {
    id: "25",
    name: "Slice of Italy",
    city: "Bangalore",
    cuisineType: "Italian",
    rating: 4.5,
    deliveryTime: "35-40 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Truffle Pizza", price: 620, description: "Black truffle and mushroom", isVeg: true, isBestseller: true },
      { name: "Carbonara", price: 380, description: "Classic Roman pasta", isVeg: false },
      { name: "Minestrone", price: 220, description: "Italian vegetable soup", isVeg: true },
      { name: "Panna Cotta", price: 200, description: "Vanilla cream dessert", isVeg: true },
    ],
  },
  {
    id: "26",
    name: "Burger Federation",
    city: "Bangalore",
    cuisineType: "Fast Food",
    rating: 4.4,
    deliveryTime: "20-25 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    menuItems: [
      {
        name: "Truffle Burger",
        price: 420,
        description: "Premium beef with truffle mayo",
        isVeg: false,
        isBestseller: true,
      },
      { name: "BBQ Pulled Pork", price: 380, description: "Slow-cooked pork burger", isVeg: false },
      { name: "Sweet Potato Fries", price: 150, description: "Crispy sweet potato", isVeg: true },
      { name: "Oreo Shake", price: 180, description: "Cookies and cream shake", isVeg: true },
    ],
  },
  {
    id: "27",
    name: "Meghana Foods",
    city: "Bangalore",
    cuisineType: "Biryani",
    rating: 4.8,
    deliveryTime: "30-35 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    menuItems: [
      {
        name: "Andhra Chicken Biryani",
        price: 280,
        description: "Spicy Andhra style",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Guntur Chicken", price: 320, description: "Extra spicy chicken", isVeg: false },
      { name: "Paneer 65", price: 220, description: "Crispy spiced paneer", isVeg: true },
      { name: "Ghee Rice", price: 150, description: "Fragrant ghee rice", isVeg: true },
    ],
  },
  {
    id: "28",
    name: "Corner House",
    city: "Bangalore",
    cuisineType: "Desserts",
    rating: 4.7,
    deliveryTime: "25-30 min",
    priceRange: "₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      {
        name: "Death By Chocolate",
        price: 180,
        description: "Legendary chocolate sundae",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Hot Chocolate Fudge", price: 150, description: "Classic hot fudge", isVeg: true },
      { name: "Banana Split", price: 160, description: "Traditional sundae", isVeg: true },
      { name: "Walnut Brownie", price: 120, description: "Warm with ice cream", isVeg: true },
    ],
  },
  {
    id: "29",
    name: "Coastal Fresh",
    city: "Bangalore",
    cuisineType: "South Indian",
    rating: 4.5,
    deliveryTime: "30-35 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Mangalore Fish Curry", price: 350, description: "Coconut fish curry", isVeg: false, isBestseller: true },
      { name: "Neer Dosa", price: 80, description: "Thin rice crepes", isVeg: true },
      { name: "Prawn Ghee Roast", price: 420, description: "Spicy roasted prawns", isVeg: false },
      { name: "Sol Kadhi", price: 60, description: "Kokum coconut drink", isVeg: true },
    ],
  },
  {
    id: "30",
    name: "Empire Restaurant",
    city: "Bangalore",
    cuisineType: "North Indian",
    rating: 4.3,
    deliveryTime: "25-30 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    discount: "Open 24/7",
    menuItems: [
      { name: "Empire Chicken", price: 320, description: "Signature dry chicken", isVeg: false, isBestseller: true },
      { name: "Mutton Seekh", price: 280, description: "Juicy kebabs", isVeg: false },
      { name: "Chicken 65", price: 250, description: "Crispy spiced chicken", isVeg: false },
      { name: "Rumali Roti", price: 40, description: "Thin bread", isVeg: true },
    ],
  },
  // Chennai Restaurants
  {
    id: "31",
    name: "Saravana Bhavan",
    city: "Chennai",
    cuisineType: "South Indian",
    rating: 4.8,
    deliveryTime: "20-25 min",
    priceRange: "₹",
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    menuItems: [
      { name: "Special Thali", price: 180, description: "Complete South Indian meal", isVeg: true, isBestseller: true },
      { name: "Ghee Pongal", price: 100, description: "Rice with lentils and ghee", isVeg: true },
      { name: "Paper Roast Dosa", price: 120, description: "Extra crispy dosa", isVeg: true },
      { name: "Kesari", price: 60, description: "Sweet semolina dessert", isVeg: true },
    ],
  },
  {
    id: "32",
    name: "Murugan Idli Shop",
    city: "Chennai",
    cuisineType: "South Indian",
    rating: 4.6,
    deliveryTime: "15-20 min",
    priceRange: "₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Soft Idli", price: 50, description: "Fluffy steamed idlis", isVeg: true, isBestseller: true },
      { name: "Mini Tiffin", price: 120, description: "Sampler platter", isVeg: true },
      { name: "Podi Dosa", price: 90, description: "Spice powder dosa", isVeg: true },
      { name: "Strong Coffee", price: 40, description: "Filter kaapi", isVeg: true },
    ],
  },
  {
    id: "33",
    name: "Buhari",
    city: "Chennai",
    cuisineType: "North Indian",
    rating: 4.5,
    deliveryTime: "30-35 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    menuItems: [
      { name: "Chicken Chettinad", price: 380, description: "Spicy pepper chicken", isVeg: false, isBestseller: true },
      { name: "Mutton Pepper Fry", price: 420, description: "Dry spiced mutton", isVeg: false },
      { name: "Parotta", price: 50, description: "Layered flatbread", isVeg: true },
      { name: "Chicken 65", price: 280, description: "Chennai's favorite", isVeg: false },
    ],
  },
  {
    id: "34",
    name: "Mainland China",
    city: "Chennai",
    cuisineType: "Chinese",
    rating: 4.4,
    deliveryTime: "35-40 min",
    priceRange: "₹₹₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Peking Duck", price: 780, description: "Classic roasted duck", isVeg: false, isBestseller: true },
      { name: "Szechuan Tofu", price: 320, description: "Spicy tofu stir-fry", isVeg: true },
      { name: "Har Gow", price: 280, description: "Crystal shrimp dumplings", isVeg: false },
      { name: "Fortune Cookie Platter", price: 150, description: "Dessert platter", isVeg: true },
    ],
  },
  {
    id: "35",
    name: "Little Italy",
    city: "Chennai",
    cuisineType: "Italian",
    rating: 4.5,
    deliveryTime: "30-35 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      {
        name: "Wood Fired Pizza",
        price: 420,
        description: "Authentic Neapolitan style",
        isVeg: true,
        isBestseller: true,
      },
      { name: "Ravioli", price: 380, description: "Stuffed pasta in sage butter", isVeg: true },
      { name: "Caprese Salad", price: 250, description: "Fresh mozzarella and tomato", isVeg: true },
      { name: "Affogato", price: 180, description: "Espresso over ice cream", isVeg: true },
    ],
  },
  {
    id: "36",
    name: "Hot Chips",
    city: "Chennai",
    cuisineType: "Fast Food",
    rating: 4.2,
    deliveryTime: "15-20 min",
    priceRange: "₹",
    image: "/placeholder.svg?height=200&width=300",
    discount: "Combo deals available",
    menuItems: [
      { name: "Chicken Burger", price: 150, description: "Chennai's favorite", isVeg: false, isBestseller: true },
      { name: "Paneer Wrap", price: 130, description: "Spiced paneer roll", isVeg: true },
      { name: "French Fries", price: 80, description: "Classic golden fries", isVeg: true },
      { name: "Cold Coffee", price: 90, description: "Chilled coffee shake", isVeg: true },
    ],
  },
  {
    id: "37",
    name: "Dindigul Thalappakatti",
    city: "Chennai",
    cuisineType: "Biryani",
    rating: 4.7,
    deliveryTime: "30-35 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    menuItems: [
      {
        name: "Thalappakatti Biryani",
        price: 320,
        description: "Signature seeraga samba biryani",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Chicken Varuval", price: 280, description: "Dry spiced chicken", isVeg: false },
      { name: "Mutton Chukka", price: 350, description: "Dry roasted mutton", isVeg: false },
      { name: "Payasam", price: 80, description: "Sweet pudding", isVeg: true },
    ],
  },
  {
    id: "38",
    name: "Cream Centre",
    city: "Chennai",
    cuisineType: "Desserts",
    rating: 4.4,
    deliveryTime: "25-30 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "American Mud Pie", price: 220, description: "Chocolate ice cream pie", isVeg: true, isBestseller: true },
      { name: "Fresh Fruit Salad", price: 180, description: "With ice cream", isVeg: true },
      { name: "Brownie Sizzler", price: 250, description: "Sizzling brownie", isVeg: true },
      { name: "Mango Mastani", price: 160, description: "Mango shake with ice cream", isVeg: true },
    ],
  },
  {
    id: "39",
    name: "Copper Chimney",
    city: "Chennai",
    cuisineType: "North Indian",
    rating: 4.5,
    deliveryTime: "35-40 min",
    priceRange: "₹₹₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Galouti Kebab", price: 420, description: "Melt in mouth kebabs", isVeg: false, isBestseller: true },
      { name: "Dum Pukht Biryani", price: 480, description: "Slow-cooked biryani", isVeg: false },
      { name: "Dal Bukhara", price: 320, description: "24-hour cooked lentils", isVeg: true },
      { name: "Kulfi", price: 120, description: "Indian ice cream", isVeg: true },
    ],
  },
  {
    id: "40",
    name: "Dosa Plaza",
    city: "Chennai",
    cuisineType: "South Indian",
    rating: 4.3,
    deliveryTime: "20-25 min",
    priceRange: "₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "70 MM Dosa", price: 180, description: "Extra long dosa", isVeg: true, isBestseller: true },
      { name: "Cheese Dosa", price: 150, description: "Loaded with cheese", isVeg: true },
      { name: "Schezwan Dosa", price: 140, description: "Indo-Chinese fusion", isVeg: true },
      { name: "Mysore Masala", price: 130, description: "Spicy red chutney", isVeg: true },
    ],
  },
  // Kolkata Restaurants
  {
    id: "41",
    name: "Oh! Calcutta",
    city: "Kolkata",
    cuisineType: "North Indian",
    rating: 4.8,
    deliveryTime: "35-40 min",
    priceRange: "₹₹₹",
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    menuItems: [
      {
        name: "Chingri Malai Curry",
        price: 520,
        description: "Prawns in coconut cream",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Kosha Mangsho", price: 450, description: "Slow-cooked mutton", isVeg: false },
      { name: "Luchi Aloor Dom", price: 180, description: "Fried bread with potato curry", isVeg: true },
      { name: "Mishti Doi", price: 100, description: "Sweet yogurt", isVeg: true },
    ],
  },
  {
    id: "42",
    name: "Peter Cat",
    city: "Kolkata",
    cuisineType: "Continental",
    rating: 4.7,
    deliveryTime: "40-45 min",
    priceRange: "₹₹₹",
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    menuItems: [
      { name: "Chelo Kebab", price: 580, description: "Legendary dish with rice", isVeg: false, isBestseller: true },
      { name: "Sizzler", price: 520, description: "Mixed grill platter", isVeg: false },
      { name: "Baked Alaska", price: 280, description: "Classic flambéed dessert", isVeg: true },
      { name: "Irish Coffee", price: 180, description: "Warm coffee cocktail", isVeg: true },
    ],
  },
  {
    id: "43",
    name: "Arsalan",
    city: "Kolkata",
    cuisineType: "Biryani",
    rating: 4.9,
    deliveryTime: "30-35 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    discount: "Kolkata's #1 Biryani",
    menuItems: [
      {
        name: "Kolkata Chicken Biryani",
        price: 280,
        description: "With potato and egg",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Mutton Chaap", price: 350, description: "Fried mutton ribs", isVeg: false },
      { name: "Firni", price: 80, description: "Rose flavored pudding", isVeg: true },
      { name: "Reshmi Kebab", price: 250, description: "Silky chicken kebabs", isVeg: false },
    ],
  },
  {
    id: "44",
    name: "Golden Joy",
    city: "Kolkata",
    cuisineType: "Chinese",
    rating: 4.5,
    deliveryTime: "25-30 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      {
        name: "Tangra Chilli Chicken",
        price: 320,
        description: "Kolkata Chinese special",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Fish in Hot Garlic", price: 380, description: "Crispy fish fillets", isVeg: false },
      { name: "Prawn Salt & Pepper", price: 420, description: "Wok-tossed prawns", isVeg: false },
      { name: "Date Pancakes", price: 150, description: "Sweet dessert", isVeg: true },
    ],
  },
  {
    id: "45",
    name: "Flurys",
    city: "Kolkata",
    cuisineType: "Desserts",
    rating: 4.6,
    deliveryTime: "25-30 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Rum Ball", price: 120, description: "Classic chocolate rum", isVeg: true, isBestseller: true },
      { name: "Chicken Puff", price: 80, description: "Flaky pastry", isVeg: false },
      { name: "Black Forest", price: 180, description: "Classic cake slice", isVeg: true },
      { name: "Darjeeling Tea", price: 100, description: "Premium loose leaf", isVeg: true },
    ],
  },
  {
    id: "46",
    name: "6 Ballygunge Place",
    city: "Kolkata",
    cuisineType: "North Indian",
    rating: 4.7,
    deliveryTime: "35-40 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Bengali Thali", price: 450, description: "Complete traditional meal", isVeg: false, isBestseller: true },
      { name: "Ilish Bhapa", price: 520, description: "Steamed hilsa fish", isVeg: false },
      { name: "Shukto", price: 180, description: "Bitter vegetable mix", isVeg: true },
      { name: "Sandesh", price: 100, description: "Bengali sweet", isVeg: true },
    ],
  },
  {
    id: "47",
    name: "Marco Polo",
    city: "Kolkata",
    cuisineType: "Italian",
    rating: 4.4,
    deliveryTime: "35-40 min",
    priceRange: "₹₹₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Lobster Thermidor", price: 950, description: "Creamy lobster dish", isVeg: false, isBestseller: true },
      { name: "Risotto Milanese", price: 420, description: "Saffron risotto", isVeg: true },
      { name: "Minestrone Soup", price: 220, description: "Italian vegetable soup", isVeg: true },
      { name: "Panna Cotta", price: 200, description: "Italian dessert", isVeg: true },
    ],
  },
  {
    id: "48",
    name: "Mocambo",
    city: "Kolkata",
    cuisineType: "Continental",
    rating: 4.5,
    deliveryTime: "40-45 min",
    priceRange: "₹₹₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Devilled Crab", price: 480, description: "Spiced crab dish", isVeg: false, isBestseller: true },
      { name: "Prawn Cocktail", price: 350, description: "Classic starter", isVeg: false },
      { name: "Chicken a la Kiev", price: 420, description: "Butter-stuffed chicken", isVeg: false },
      { name: "Baked Alaska", price: 280, description: "Ice cream and meringue", isVeg: true },
    ],
  },
  {
    id: "49",
    name: "Kusum Rolls",
    city: "Kolkata",
    cuisineType: "Fast Food",
    rating: 4.3,
    deliveryTime: "15-20 min",
    priceRange: "₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Chicken Kathi Roll", price: 120, description: "Classic Kolkata roll", isVeg: false, isBestseller: true },
      { name: "Egg Roll", price: 80, description: "Egg wrapped in paratha", isVeg: false },
      { name: "Mutton Roll", price: 150, description: "Spiced mutton", isVeg: false },
      { name: "Paneer Roll", price: 100, description: "Vegetarian option", isVeg: true },
    ],
  },
  {
    id: "50",
    name: "Balaram Mullick",
    city: "Kolkata",
    cuisineType: "Desserts",
    rating: 4.8,
    deliveryTime: "20-25 min",
    priceRange: "₹",
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    menuItems: [
      { name: "Rasogolla", price: 30, description: "Spongy milk balls", isVeg: true, isBestseller: true },
      { name: "Chomchom", price: 40, description: "Stuffed sweet", isVeg: true },
      { name: "Rabri", price: 80, description: "Thick sweetened milk", isVeg: true },
      { name: "Langcha", price: 35, description: "Fried milk sweet", isVeg: true },
    ],
  },
  // Hyderabad Restaurants
  {
    id: "51",
    name: "Paradise Biryani",
    city: "Hyderabad",
    cuisineType: "Biryani",
    rating: 4.9,
    deliveryTime: "30-35 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    discount: "Since 1953 - Legacy of Taste",
    menuItems: [
      {
        name: "Paradise Chicken Biryani",
        price: 340,
        description: "The legendary biryani",
        isVeg: false,
        isBestseller: true,
      },
      { name: "Double Ka Meetha", price: 120, description: "Bread pudding", isVeg: true },
      { name: "Mirchi Ka Salan", price: 150, description: "Spicy chilli curry", isVeg: true },
      { name: "Haleem", price: 220, description: "Slow-cooked meat porridge", isVeg: false },
    ],
  },
  {
    id: "52",
    name: "Shah Ghouse",
    city: "Hyderabad",
    cuisineType: "Biryani",
    rating: 4.7,
    deliveryTime: "25-30 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Mutton Biryani", price: 380, description: "Authentic Hyderabadi", isVeg: false, isBestseller: true },
      { name: "Paya", price: 250, description: "Trotters curry", isVeg: false },
      { name: "Rumali Roti", price: 30, description: "Thin handkerchief bread", isVeg: true },
      { name: "Khubani Ka Meetha", price: 100, description: "Apricot dessert", isVeg: true },
    ],
  },
  {
    id: "53",
    name: "Bawarchi",
    city: "Hyderabad",
    cuisineType: "North Indian",
    rating: 4.5,
    deliveryTime: "30-35 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    menuItems: [
      { name: "Special Biryani", price: 320, description: "House special", isVeg: false, isBestseller: true },
      { name: "Tandoori Platter", price: 450, description: "Mixed grills", isVeg: false },
      { name: "Dum Ka Murgh", price: 380, description: "Slow-cooked chicken", isVeg: false },
      { name: "Sheer Khurma", price: 120, description: "Festival dessert", isVeg: true },
    ],
  },
  {
    id: "54",
    name: "Ohri's",
    city: "Hyderabad",
    cuisineType: "Continental",
    rating: 4.4,
    deliveryTime: "35-40 min",
    priceRange: "₹₹₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Tenderloin Steak", price: 750, description: "Premium beef cut", isVeg: false, isBestseller: true },
      { name: "Grilled Fish", price: 520, description: "Fresh catch of the day", isVeg: false },
      { name: "Caesar Salad", price: 280, description: "Classic salad", isVeg: true },
      { name: "Chocolate Fountain", price: 350, description: "For sharing", isVeg: true },
    ],
  },
  {
    id: "55",
    name: "Nizam's Kathi",
    city: "Hyderabad",
    cuisineType: "Fast Food",
    rating: 4.3,
    deliveryTime: "20-25 min",
    priceRange: "₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Double Chicken Roll", price: 180, description: "Extra loaded", isVeg: false, isBestseller: true },
      { name: "Seekh Paratha Roll", price: 150, description: "Kebab roll", isVeg: false },
      { name: "Paneer Tikka Roll", price: 120, description: "Vegetarian choice", isVeg: true },
      { name: "Cold Drink", price: 40, description: "Refreshing beverage", isVeg: true },
    ],
  },
  {
    id: "56",
    name: "Chutneys",
    city: "Hyderabad",
    cuisineType: "South Indian",
    rating: 4.6,
    deliveryTime: "20-25 min",
    priceRange: "₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Pesarattu", price: 100, description: "Green moong dosa", isVeg: true, isBestseller: true },
      { name: "Upma Pesarattu", price: 120, description: "With upma filling", isVeg: true },
      { name: "Gongura Dosa", price: 110, description: "Tangy Andhra chutney", isVeg: true },
      { name: "Buttermilk", price: 40, description: "Spiced chaas", isVeg: true },
    ],
  },
  {
    id: "57",
    name: "Absolute Barbecue",
    city: "Hyderabad",
    cuisineType: "North Indian",
    rating: 4.5,
    deliveryTime: "40-45 min",
    priceRange: "₹₹₹",
    image: "/placeholder.svg?height=200&width=300",
    discount: "Live grill experience",
    menuItems: [
      { name: "BBQ Platter", price: 650, description: "Assorted grilled meats", isVeg: false, isBestseller: true },
      { name: "Paneer Tikka", price: 350, description: "Grilled cottage cheese", isVeg: true },
      { name: "Lamb Chops", price: 580, description: "Herb-marinated lamb", isVeg: false },
      { name: "Grilled Pineapple", price: 180, description: "Caramelized dessert", isVeg: true },
    ],
  },
  {
    id: "58",
    name: "Nanking",
    city: "Hyderabad",
    cuisineType: "Chinese",
    rating: 4.4,
    deliveryTime: "30-35 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Cantonese Noodles", price: 280, description: "Stir-fried noodles", isVeg: true, isBestseller: true },
      { name: "Dragon Chicken", price: 350, description: "Spicy Indo-Chinese", isVeg: false },
      { name: "Vegetable Manchow", price: 150, description: "Thick soup", isVeg: true },
      { name: "Honey Noodles", price: 180, description: "Crispy sweet noodles", isVeg: true },
    ],
  },
  {
    id: "59",
    name: "Cream Stone",
    city: "Hyderabad",
    cuisineType: "Desserts",
    rating: 4.5,
    deliveryTime: "25-30 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    menuItems: [
      { name: "Stone Ice Cream", price: 180, description: "Custom mixed on stone", isVeg: true, isBestseller: true },
      { name: "Brownie Overload", price: 220, description: "With hot fudge", isVeg: true },
      { name: "Fruit Fiesta", price: 200, description: "Fresh fruits blend", isVeg: true },
      { name: "Oreo Tornado", price: 190, description: "Cookies and cream", isVeg: true },
    ],
  },
  {
    id: "60",
    name: "Pista House",
    city: "Hyderabad",
    cuisineType: "Desserts",
    rating: 4.7,
    deliveryTime: "20-25 min",
    priceRange: "₹₹",
    image: "/placeholder.svg?height=200&width=300",
    isPromoted: true,
    menuItems: [
      { name: "Pista House Haleem", price: 250, description: "Award-winning haleem", isVeg: false, isBestseller: true },
      { name: "Badam Milk", price: 80, description: "Almond milk drink", isVeg: true },
      { name: "Qubani Ka Meetha", price: 120, description: "Apricot dessert", isVeg: true },
      { name: "Gil-e-Firdaus", price: 150, description: "Royal rice dessert", isVeg: true },
    ],
  },
]
